apiVersion: apps/v1
kind: Deployment

metadata:
  name: frontend-service
  labels:
    app: frontend-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend-service
  template: 
    metadata:
      labels:
        app: frontend-service
    spec:
      imagePullSecrets:
        - name: ecr-secret
      containers:
        - name: frontend-service
          image: 045555583673.dkr.ecr.us-east-1.amazonaws.com/nexusmarket/frontend:92268f30d2292aff787f7ea8a771a11022558873
          ports:
            - containerPort: 80