name: NexusMarket CI
on:
  push: 
    branches: ["main","develop","master"]
  pull_request:
    branches: ["main","develop","master"]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: nexus_market
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Test Order Service
        run: cd services/order-service && npm install && NODE_ENV=test npm test
        env:
          REDIS_URL: redis://localhost:6379/0

      - name: Test Payment Service
        run: cd services/payment-service && npm install && NODE_ENV=test npm test

      - name: Test Notification Service
        run: cd services/notification-service && npm install && NODE_ENV=test npm test
        env:
          REDIS_URL: redis://localhost:6379/0

      - name: Test Auth Service
        env:
          POSTGRES_HOST: localhost
        run: |
          cd services/auth-service
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python manage.py test

      - name: Test Catalog Service
        env:
          POSTGRES_HOST: localhost
          REDIS_URL: redis://localhost:6379/0
        run: |
          cd services/catalog-service
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python manage.py test

  build-and-push:
    name: Build and Push Docker Images
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: setup docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Check AWS identity
        run: |
          aws sts get-caller-identity

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set image prefix
        run: |
          echo "ECR_REGISTRY=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com" >> $GITHUB_ENV
          echo "IMAGE_TAG=${{ github.sha }}" >> $GITHUB_ENV

      - name: Build & Push Auth Service
        run: |
          docker build -t $ECR_REGISTRY/nexusmarket/auth-service:$IMAGE_TAG \
                       -t $ECR_REGISTRY/nexusmarket/auth-service:latest \
                       ./services/auth-service
          docker push $ECR_REGISTRY/nexusmarket/auth-service:$IMAGE_TAG
          docker push $ECR_REGISTRY/nexusmarket/auth-service:latest

      - name: Build & Push Catalog Service
        run: |
          docker build -t $ECR_REGISTRY/nexusmarket/catalog-service:$IMAGE_TAG \
                       -t $ECR_REGISTRY/nexusmarket/catalog-service:latest \
                       ./services/catalog-service
          docker push $ECR_REGISTRY/nexusmarket/catalog-service:$IMAGE_TAG
          docker push $ECR_REGISTRY/nexusmarket/catalog-service:latest
      
      - name: Build & Push Order Service
        run: |
          docker build -t $ECR_REGISTRY/nexusmarket/order-service:$IMAGE_TAG \
                       -t $ECR_REGISTRY/nexusmarket/order-service:latest \
                       ./services/order-service
          docker push $ECR_REGISTRY/nexusmarket/order-service:$IMAGE_TAG
          docker push $ECR_REGISTRY/nexusmarket/order-service:latest   
      
      - name: Build & Push Payment Service
        run: |
          docker build -t $ECR_REGISTRY/nexusmarket/payment-service:$IMAGE_TAG \
                       -t $ECR_REGISTRY/nexusmarket/payment-service:latest \
                       ./services/payment-service
          docker push $ECR_REGISTRY/nexusmarket/payment-service:$IMAGE_TAG
          docker push $ECR_REGISTRY/nexusmarket/payment-service:latest  
      
      - name: Build & Push Notification Service
        run: |
          docker build -t $ECR_REGISTRY/nexusmarket/notification-service:$IMAGE_TAG \
                       -t $ECR_REGISTRY/nexusmarket/notification-service:latest \
                       ./services/notification-service
          docker push $ECR_REGISTRY/nexusmarket/notification-service:$IMAGE_TAG
          docker push $ECR_REGISTRY/nexusmarket/notification-service:latest
      
      # ========== FRONTEND ==========
      - name: Build & Push Frontend
        run: |
          docker build -t $ECR_REGISTRY/nexusmarket/frontend:$IMAGE_TAG \
                       -t $ECR_REGISTRY/nexusmarket/frontend:latest \
                       ./services/frontend
          docker push $ECR_REGISTRY/nexusmarket/frontend:$IMAGE_TAG
          docker push $ECR_REGISTRY/nexusmarket/frontend:latest

      - name: All images pushed successfully
        run: echo " All services built and pushed to ECR!"

